githubname: py-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - numpy>=2.0,<3.0
  - matplotlib>=3.9
  - pandas>=2.2
  - seaborn>=0.13
  - scikit-learn>=1.5
  - requests>=2.32
  - jupyter>=1.1
  - ipykernel>=6.29
